ktor:
  deployment:
    port: "$APP_PORT:8081"
  application:
    modules:
      - main.SerializationKt.configureSerialization
      - main.ExposedKt.configureExposed
      - main.StatusPageKt.configureStatusPage
      - main.RoutingKt.configureRouting
      - main.AppKt.configureApp
app:
  version: "1.0.4"
postgres:
  url: "$DB_URL:jdbc:postgresql://localhost:5432/BSI"
  user: postgres
  password: 1234